#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Krishna Teja Vepa
# One-command verification for every registered instance, from a clean clone.
#
# For each instance directory under instances/:
#   1. verifies the provenance manifest hashes (committed files untampered),
#   2. regenerates the artifact in a temp sandbox from the committed inputs
#      (never touching the committed copy), and
#   3. byte-compares the regenerated artifact against the committed one.
#
# --self-test: runs the same machinery against the synthetic fixture in
#   tests/fixture/instance (expect PASS), then tampers with a sandbox copy
#   and asserts the manifest check FAILS (tamper detection proven).
#
# Exit 0: all checks pass. Exit 1: mismatch (diff printed). Exit 2: setup.
#
# Usage: bash scripts/verify.sh [--self-test]
set -u
cd "$(dirname "$0")/.."
REPO="$PWD"
PY="${QME_PY:-python3}"

command -v "$PY" >/dev/null || { echo "verify: no python3 on PATH" >&2; exit 2; }

verify_instance() {
    local D="$1"
    echo "== instance: $D =="
    "$PY" scripts/make_manifest.py --check --dir "$D" || {
        echo "verify: manifest check FAILED for $D" >&2
        return 1
    }
    local artifact generator
    artifact=$("$PY" -c "import json;print(json.load(open('$D/instance.json'))['artifact'])") || return 2
    generator=$("$PY" -c "import json;print(json.load(open('$D/instance.json'))['generator'])") || return 2
    local SANDBOX
    SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/qme_registry.XXXXXX")" || return 2
    # shellcheck disable=SC2064
    trap "rm -rf '$SANDBOX'" RETURN
    cp -R "$D" "$SANDBOX/inst"
    rm -f "$SANDBOX/inst/$artifact"
    (cd "$SANDBOX/inst" && "$PY" "$generator" >regen.log 2>&1) || {
        echo "verify: generator failed for $D; log follows" >&2
        cat "$SANDBOX/inst/regen.log" >&2
        return 2
    }
    if cmp -s "$SANDBOX/inst/$artifact" "$D/$artifact"; then
        echo "PASS: $artifact regenerated byte-identically from committed inputs."
        return 0
    else
        echo "DIFF REPORT: regenerated artifact differs from the committed copy:" >&2
        diff -u "$D/$artifact" "$SANDBOX/inst/$artifact" >&2
        return 1
    fi
}

if [ "${1:-}" = "--self-test" ]; then
    FIX="tests/fixture/instance"
    [ -d "$FIX" ] || { echo "self-test: fixture missing" >&2; exit 2; }
    echo "=== self-test 1/2: fixture verifies (expect PASS) ==="
    verify_instance "$FIX" || { echo "self-test: fixture verification FAILED" >&2; exit 1; }
    echo "=== self-test 2/2: tampered copy is detected (expect FAIL, caught) ==="
    TAMPER="$(mktemp -d "${TMPDIR:-/tmp}/qme_tamper.XXXXXX")" || exit 2
    trap 'rm -rf "$TAMPER"' EXIT
    cp -R "$FIX" "$TAMPER/inst"
    printf '\n9999.0\n' >> "$TAMPER/inst/inputs/values.csv"
    if "$PY" scripts/make_manifest.py --check --dir "$TAMPER/inst" >/dev/null 2>&1; then
        echo "self-test: TAMPER NOT DETECTED; the manifest check is broken" >&2
        exit 1
    fi
    echo "PASS: tampered input detected by the manifest check."
    echo "self-test complete: machinery verifies and tampering is caught."
    exit 0
fi

# Default mode: verify every registered instance.
shopt -s nullglob
FAILED=0
FOUND=0
for D in instances/*/; do
    [ -f "${D}instance.json" ] || continue
    FOUND=1
    verify_instance "${D%/}" || FAILED=1
done
if [ "$FOUND" -eq 0 ]; then
    echo "registered instances: 0 (registry is new)."
    echo "The verification machinery itself is exercised by: bash scripts/verify.sh --self-test"
    exit 0
fi
exit "$FAILED"
